# Generated by Django 4.0.4 on 2022-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passdetails',
            name='redeem_status',
            field=models.BooleanField(default=False),
        ),
    ]
