# Generated by Django 4.0.4 on 2022-05-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_passdetails_redeem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passdetails',
            name='payment_Id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
