# Generated by Django 4.0.4 on 2022-06-22 07:57

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_passdetails_item_count_alter_passdetails_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=30, unique=True)),
                ('roll_no', models.CharField(max_length=30, unique=True)),
                ('student_image', models.FileField(upload_to='uploads/%Y/%m%d/', validators=[apis.models.validate_file_extension], verbose_name='Upload Article (PDF Only)')),
            ],
        ),
    ]
