# Generated by Django 4.0.4 on 2022-06-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_studentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='course',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='student_image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m%d/', verbose_name='Upload Image'),
        ),
    ]
